### PR TITLE
Allow custom repo lists for git-all and mvn-all scripts

### PR DESCRIPTION
**Pull request by psiroky**
@mbiarnes could you please review this?

### CODE REVIEW

**Comment by ge0ffrey** [comment]
this is useful indeed. Now I have separate checkouts for "all repos", "just drools" (includes knowledge, docs), "just-wb" (all wb repo's), etc

**Comment by psiroky** [comment]
In future I would also like to add an option to specify own repository list as a file (e.g. --repository-list-file=)

Also, one other thing that looks useful it something like Maven's `-rf` (run from), so that if the build fails in the middle you can easily just say to start building from the repository that failed (instead of having to rebuild all the previous ones as well).

**Comment by etirelli** [comment]
Quite helpful! Thank you Petr!

**Comment by ge0ffrey** [comment]
or -rt (--run-to). When working on the engines, it's handy to say "-rt optaplanner" for me or "-rt drools" for @mariofusco

**Comment by kiereleaseuser** [comment]
+1

**Pull request merged**
