### PR TITLE
Added missing word "build" in README

### PR DESCRIPTION
**Pull request by oskopek**

### CODE REVIEW

**Comment by mrietveld** [comment]
@ge0ffrey If it's possible, would you mind merging PR's with rebase instead of using the github "merge" button? That way the history stays neater.. :) (no merge bubbles). Thanks!

**Comment by ge0ffrey** [comment]
That's a non-trivial overhead, are we sure we want to do that as a team?

**Comment by manstis** [comment]
Been doing it for ages already.. This way I can make sure (a) revised code
compiles and (b) tests pass before merging.

**Comment by oskopek** [comment]
Do we have any (semi)official PR guide/process?

**Comment by mrietveld** [comment]
That's a very good question: no, we don't. I'll be sending an e-mail out about it to the internal team list today.

**Comment by ge0ffrey** [comment]
IIRC, Petr is working getting jenkins (or travis?) to comment on each PR to
indicate wether it compiles and passes all unit tests.


2015-08-05 19:55 GMT+02:00 Michael Anstis <notifications@github.com>:

> Been doing it for ages already.. This way I can make sure (a) revised code
> compiles and (b) tests pass before merging.
> On 5 Aug 2015 18:00, "Geoffrey De Smet" <notifications@github.com> wrote:
>
> > That's a non-trivial overhead, are we sure we want to do that as a team?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/84#issuecomment-128050043
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/84#issuecomment-128091044>
> .
>



-- 
With kind regards / Met vriendelijke groeten,
Geoffrey De Smet

**Comment by manstis** [comment]
Perhaps on "droolsjbpm/drools".. some of the poorer relatives (especially
anything with a webapp) are no where near as fortunate. Also cherry-picking
commits without a linear history are a PITA - and leave the comments in the
commit history a mess.

**Comment by mrietveld** [comment]
@ge0ffrey , I disagree: rebasing is trivial, IMHO.

    gpr () { $git fetch $1 pull/$2/head:$3; git checkout $3; }
    git checkout master
    git fetch upstream
    git merge --ff upstream/master
    gpr upstream <pull-request-number> <make-up-a-name>
    git rebase master
    # do what you want to do to check if the PR is good? 
    git checkout master
    git merge --ff <make-up-a-name>
    git push upstream master

**Comment by manstis** [comment]
+1

**Comment by psiroky** [comment]
I do agree that rebasing makes the history much cleaner. But I also see the point in using the "Merge button". For trivial things, like this PR, doing the rebase is overhead. Pushing the button is much easier than following the procedure Marco described above.

I am working on the automated PR builds, but as you can imagine it is not that trivial. The UI repos (anything with webapp) are even more special as many of the PRs span multiple repositories, so using current Jenkins plugins is not possible. I will keep you posted.

**Pull request merged**
