### PR TITLE
DROOLS-1019 add kmodule.xsd publishes to the release procedure

### PR DESCRIPTION
**Pull request by ge0ffrey**

### CODE REVIEW

**Comment by ge0ffrey** [comment]
See also https://issues.jboss.org/browse/DROOLS-1019 for motivation why we need those XSD's there.

@mbiarnes @psiroky Let me know if the new step during the release procedure isn't clear

**Comment by psiroky** [comment]
Thanks @ge0ffrey, the steps are clear. I think we should automate this, otherwise there will always be chance that we forget....

**Comment by ge0ffrey** [comment]
@psiroky Can you merge?

**Comment by psiroky** [comment]
Merged. @mbiarnes it would be great if you could take a look at automating this.

**Pull request closed without merging**
