### PR TITLE
Update revapi version

### PR DESCRIPTION
**Pull request by MarianMacik**
Hi,

I have updated revapi plugin version.

Thanks for merging.

Marian

### CODE REVIEW

**Comment by MarianMacik** [comment]
@mbiarnes @psiroky Can we please update maven from 3.2.3 to 3.2.5? Because otherwise we cannot use the latest revapi plugin. See the build of the referenced PR droolsjbpm/droolsjbpm-knowledge#182

Thanks.

**Comment by psiroky** [comment]
@MarianMacik yes, that should be possible, but we will need some time to update the Jenkins env and possible other configs as well.

**Comment by MarianMacik** [comment]
@psiroky great! Thanks for your help.

**Comment by psiroky** [comment]
+1. Needs to be merged after https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/313

**Pull request merged**
