### PR TITLE
Upgrade IP BOM to 7.0.0.CR6

### PR DESCRIPTION
**Pull request by psiroky**

### CODE REVIEW

**Comment by psiroky** [comment]
Jenkins execute full downstream build

**Comment by psiroky** [comment]
Jenkins execute full downstream build

**Comment by psiroky** [comment]
@mbiarnes could you please review this?

**Comment by mbiarnes** [comment]
@psiroky looks ok for me if
version.org.apache.commons.commons-dbcp2
version.org.apache.commons.commons-pool2
version.org.jboss.errai.cdi10-compatible
were removed from out projects since I can't find them in the IP bom 7.0.0.0.CR6

**Comment by psiroky** [comment]
The `version.org.jboss.errai.cdi10-compatible` is no longer needed. The others are there but renamed to follow the converntions, e.g. `<version.org.apache.commons.dbcp2>2.1.1</version.org.apache.commons.dbcp2>`

**Comment by mbiarnes** [comment]
+1

**Pull request merged**
