### PR TITLE
Upgrade lienzo core to 2.0.277 and lienzo tests to 1.0.0-RC3.

### PR DESCRIPTION
**Pull request by romartin**

### CODE REVIEW

**Comment by romartin** [comment]
Hi @manstis , this is the lienzo upgrade we've commented on today's call.. once get merged I will be able to create the PR for integrating stunner into kie-wb-common. Thanks!

**Comment by romartin** [comment]
Added lienzo nativetools & commons as well.

**Comment by psiroky** [comment]
We should also create PR(s) for IP BOM...

**Comment by mbiarnes** [comment]
ok - this was the only question I had - don't have these dependencies to be added to IP_BOM? but @psiroky answered this. I will do the PR for IP-BOM

**Comment by manstis** [comment]
@mbiarnes @romartin Thanks Michael for looking after ip-bom.

**Comment by manstis** [comment]
@romartin You'll also need to update https://github.com/uberfire/uberfire/blob/master/pom.xml

**Comment by romartin** [comment]
@manstis @mbiarnes @psiroky Thanks guys for moving this forward!!

**Comment by romartin** [comment]
@manstis Thanks for the feedback! Created this for UF -> https://github.com/uberfire/uberfire/pull/523

**Pull request merged**
