### PR TITLE
Enforce Java 8+ and remove PermGen settings

### PR DESCRIPTION
**Pull request by psiroky**
@csadilek please merge this together with your Errai 4 upgrade.

### CODE REVIEW

**Comment by ge0ffrey** [comment]
Does anyone else feel like celebrating when they see this? :)

**Comment by psiroky** [comment]
And the Jenkins the is not happy at all :) I will need to create new PR jobs for master and use Java 8 there.

**Comment by psiroky** [comment]
jenkins retest this

**Comment by psiroky** [comment]
@csadilek I've updated the PR, it now also removes the animal-sniffer config which is not needed anymore (should be removed from uf and dashbuilder as well)

**Comment by psiroky** [comment]
@csadilek please don't merge this yet. I just found out that drools won't compile with these changes (looks like changing the source+target levels has something to do with this). You can still push you Errai 4 upgrade, but we should not increase the default source + target levels yet. I will let you know once I manage to fix it.

**Comment by psiroky** [comment]
@csadilek I've fixed all the build-related issues I know of, so please go ahead and merge when doing the upgrade.

**Comment by csadilek** [comment]
+1 (on the way)

**Comment by csadilek** [comment]
master: 955f539bc5ee73069c511dc851994efb06c0381e

**Pull request closed without merging**
