### PR TITLE
[RHBRMS-2673] upgraded tika to prevent XML External Entity vulnerability

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
so upgraded all transitive dependencies of tika 1.14:
<version.commons-io>2.5</version.commons-io>
<version.org.apache.commons.compress>1.12</version.org.apache.commons.compress>
<version.org.apache.poi>3.15</version.org.apache.poi>

**Comment by mbiarnes** [comment]
@psiroky can you look at this please?

**Comment by psiroky** [comment]
@mbiarnes looks good. Did you try to run the whole build with these changes?

**Comment by mbiarnes** [comment]
@psiroky not on 6.5.x - only on master - I can do it

**Comment by psiroky** [comment]
Master already differs from 6.5.x quite a lot. I believe we need to run it there as well. And since Jenkins is not working at all today, we may have to do it locally.

**Comment by mbiarnes** [comment]
@psiroky tested locally with all the changes - build was successful

**Comment by psiroky** [comment]
Looks OK when looking at the PR changes. I won't be able to do a local build, but since @mbiarnes did one we should be fine.

**Comment by psiroky** [comment]
@mbiarnes there is a commit in this PR which was already merged by https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/333. Could you please remove it? (otherwise the Github won't let me to "rebase&merge" this)

**Pull request closed without merging**
