### PR TITLE
Upgrade Cargo from 1.4.19 to 1.5.0 to support latest EAP 6.4.x

### PR DESCRIPTION
**Pull request by psiroky**

### CODE REVIEW

**Comment by psiroky** [comment]
@mswiderski FYI. This should be safe upgrade I believe. @sutaakar WDYT?

**Comment by mswiderski** [comment]
@psiroky could we name the branch same as https://github.com/droolsjbpm/droolsjbpm-integration/pull/580 so we get direct verification when retriggering the droolsjbpm-integration PR?

**Comment by psiroky** [comment]
@mswiderski yes I can do that, but it needs new PR. Will create one in a sec (I did try locally, so should be fine. But I agree its better run Jenkins build as well).

**Comment by psiroky** [comment]
Replaced by https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/255

**Pull request closed without merging**
