### PR TITLE
Upgrade IP BOM from 7.0.0.CR7 to 7.0.0.CR8

### PR DESCRIPTION
**Pull request by psiroky**

### CODE REVIEW

**Comment by psiroky** [comment]
Jenkins execute full downstream build

**Comment by psiroky** [comment]
Jenkins execute full downstream build

**Comment by mswiderski** [comment]
@psiroky is this bringing in upgraded hibernate? if so then +1 from me for sure :)

**Comment by psiroky** [comment]
@mswiderski unfortunately it does not. That's gonna be part of CR9.

**Comment by mswiderski** [comment]
ok, too bad as there is another bug in the version we currently use https://hibernate.atlassian.net/browse/HHH-11552

any plans to move to CR9 before we go out with 7.0?

**Comment by psiroky** [comment]
@mswiderski I guess after we do beta7, we can do the CR9 update.

**Comment by mbiarnes** [comment]
+1

**Pull request merged**
