### PR TITLE
RHBPMS-4032 - removing fop dependency

### PR DESCRIPTION
**Pull request by jlindop**

### CODE REVIEW

**Comment by jlindop** [comment]
Required by https://github.com/droolsjbpm/jbpm-designer/pull/316

**Comment by psiroky** [comment]
@jlindop could you please remove also the respective entry in depMgmt? e.g. https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/blob/6.4.x/kie-platform-bom/pom.xml#L355. Thanks!

**Comment by jlindop** [comment]
@psiroky Done. Thanks for noticing this.

**Comment by psiroky** [comment]
+1, looks good now. Thanks @jlindop.

**Pull request merged**
