### PR TITLE
BZ-1274685 - New Repository dialog validation broken when Managed Repository is checked

### PR DESCRIPTION
**Pull request by wmedvede**
Simple modification to allow dependency setting to tests stuff.

### CODE REVIEW

**Comment by wmedvede** [comment]
The following PR is related to this PR and should be previously merged

1) https://github.com/uberfire/uberfire-extensions/pull/103

**Comment by wmedvede** [comment]
@manstis 
Hello Mike, would you mind to review this PR?

**Comment by manstis** [comment]
+1 to merge.

**Comment by csadilek** [comment]
Thanks.

6.3.x: ec17dd2bca1a82ee18e7156fc27c85eb6871d341

**Pull request closed without merging**
