### PR TITLE
Updating the oldbranches.pl script

### PR DESCRIPTION
**Pull request by mrietveld**
Minor updates/fixes to make the half-yearly or yearly checks easier.

### CODE REVIEW

**Comment by mrietveld** [comment]
@psiroky Would you mind looking at this?

**Comment by psiroky** [comment]
yay, Perl stuff :) I will take a look (and test locally).

**Comment by mrietveld** [comment]
O, hold on, I need to add a die/fail message for the -r option.

**Comment by mrietveld** [comment]
Okay, fixed! 
@psiroky Please review!

**Comment by psiroky** [comment]
+1. Merged into master.

One thing I noticed is that the script excludes some branches which probably should not be excluded, like `uf_0.5.x` or `lienzo-core-2.0.x`. I think we could check if the branch starts with number and ends with `x` (this the pattern that we follow for long-running branches). But this really is just minor thing. Thanks @mrietveld for the changes, this script is very useful!

**Pull request closed without merging**
