### PR TITLE
Change to use same Rhino version as Errai (old: 1.7R2 - new: 1.7R4)

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Comment by psiroky** [comment]
@paulovmr could could please move this  to the ip-bom? We could then share the same version in Errai and here without the need to duplicate the dependency management.

**Comment by paulovmr** [comment]
@psiroky Sure, new PR created: https://github.com/jboss-integration/jboss-integration-platform-bom/pull/343

**Comment by paulovmr** [comment]
@psiroky Hi, after talking to @csadilek , we think it's best to merge this PR for now, and undo it after we have a new release for jboss-integration-platform-bom, containing [this PR](https://github.com/jboss-integration/jboss-integration-platform-bom/pull/343/files).

**Comment by csadilek** [comment]
@psiroky so this would just be temporary until we get the ip bom release. So we can merge https://github.com/droolsjbpm/kie-wb-common/pull/596 and https://github.com/droolsjbpm/jbpm-designer/pull/518. What do you think?

**Comment by psiroky** [comment]
Yes, that's fine.

**Comment by csadilek** [comment]
+1

**Pull request merged**
