### PR TITLE
JBPM-4833 - Data Modeller MVP, Tests, and related improvments

### PR DESCRIPTION
**Pull request by wmedvede**
Hello @manstis 
would you mind review this PR?

### CODE REVIEW

**Comment by psiroky** [comment]
Hi @wmedvede. Could you please change the commit message to more meaningful one? e.g. `JBPM-4833 - kie-bom: add data modeler tests jar`.  The current one does not describe what the commit really does.

**Comment by mrietveld** [comment]
@psiroky The commit mentions the JIRA. More than that is not needed, Petr.

**Comment by wmedvede** [comment]
cherry-pick into 6.3.x DO NOT APPLY for this PR

**Comment by psiroky** [comment]
@mrietveld I disagree, but won't hold up the PR because of that. So +0 from me.

**Comment by manstis** [comment]
@mrietveld "...The commit mentions the JIRA..." and ordinarily this would be fine; however the JIRA doesn't say anything about the changes either.. but I'm not going to stop a refactor to improved MVP be stopped because of a commit description...

**Comment by manstis** [comment]
+1 to merge.

**Comment by mrietveld** [comment]
@manstis I increasingly convinced that the PR process -- while a *very* good idea -- is being slowed down by too much nitpicking. 

@psiroky and @manstis I agree with your comments, but the thing to do is, IMHO, ask walter to add info the jira. The more efficient we become with PR's, the better. 

@wmedvede Would you add a sentence to the jira to clarify it? Thanks!

**Comment by manstis** [comment]
@mrietveld hey! I +1'ed it without quibble ;)

**Comment by manstis** [comment]
@wmedvede re: "cherry-pick into 6.3.x DO NOT APPLY for this PR".. you'd need to raise a new PR for this to ever make it to a different branch.. we're meant to create separate PRs for separate branches (and I know you only want this on master.. I'm just clarifying).

**Comment by wmedvede** [comment]
@manstis @mrietveld 
Guys, this JIRA is a long term one, i.e., I need to select a set of components, review their MVP, tests, etc., merge them, and so on.

As soon the PR is merged into master, then I have "real" commits to update the JIRA. And the intention is obviously to to the JIRA and update it adding the link to the real commit into master, plus the description of the things that has been refactored as part of this commit. I think it's worthless to update the JIRA with a pointer to the PR, and the RE-UPDATE the JIRA with a pointer to the real commit into master.
On the other hand, with reference to this particular silly PR, it don't believe to have a so long discussion  is worth.

**Comment by psiroky** [comment]
@wmedvede just FYI: you don't need to update the JIRA manually with PRs or commits. JIRA automatically picks them up. See https://issues.jboss.org/browse/JBPM-4833 on the right, under "Development". This is much better than the BZ.

**Comment by psiroky** [comment]
I still believe that the commit message should describe the actual changes (may be just matter of personal preference). The issue title can always be looked up in the JIRA in case needed. But for sure, this is not a reason to hold off the PR.

**Comment by wmedvede** [comment]
@psiroky I didn't realize this automatic JIRA update with the commit info, but it's definitely a very good feature.

**Comment by csadilek** [comment]
master: 832df390cb7efd07681e0626b5de228ae5d4848c

**Comment by wmedvede** [comment]
@csadilek @psiroky 
Same comment as for the related PR in kie-wb-commit. The PR says "Closed with unmerged commits", and the associated JIRA wasn't automatically updated.

**Comment by psiroky** [comment]
@wmedvede I can see the commits listed in the JIRA (right side, "Development" section, 3 commits). The description won't be updated in case that's what you mean. You will still need to mark the JIRA as done manually.

About "Closed with unmerged commits". This happens when cherry-picking your fix into the blessed branch. After the cherry-pick the commit has different SHA-1 and thus github is not able to link back to this PR. It may be slighty improved by using `closes #<pr-nr>` in commit message (this needs to be done by the gatekeeper). That will at least link the commit into the PR so that you can see it.

**Pull request closed without merging**
