### PR TITLE
Added LogUtils class to contain LogType and LogOrder classes

### PR DESCRIPTION
**Pull request by emilianoandre**
Added prettytime dependency to use in the Logs screen in console

### CODE REVIEW

**Comment by psiroky** [comment]
This PR is pretty old. Do we still need to add this dependency?

**Comment by psiroky** [comment]
@emilianoandre @Salaboy do we still need this changes in?

**Comment by ge0ffrey** [comment]
@psiroky I wouldn't be surprised there's an accompanying PR on one of the jbpm repo's, with the actual feature. I don't see a link though.

But despite that, +1 to reject this PR rather than let it rot here. It's a shame that whatever feature was contributed wasn't picked up (aka sponsored) by someone, but it's almost a year, so now it is simply too late.

**Comment by psiroky** [comment]
I could not find a related PR in any of other repos, so closing this one. Please re-open if the changes are still needed.

**Pull request closed without merging**
