### PR TITLE
Use canonical URLs for Maven deploy repositories

### PR DESCRIPTION
**Pull request by psiroky**
This fixes/workarounds the current issues with SNAPSHOT deploys.

### CODE REVIEW

**Comment by ge0ffrey** [comment]
Is the jbossorg team (David/Vladimir/Vlastimil) ok with this? Do they intend to support that URL forever?
If not, this will break the reproducible of our builds.

**Comment by psiroky** [comment]
They are suggesting it as a workaround. Not sure if they intend to support it forever, will try to find out.

We could always revert back to the old URLs. Currently the only other option I see is to manually fix ~50 Jenkins jobs and adding the property there, which is something I would really like to avoid).

**Comment by psiroky** [comment]
Quoting David Hladký:
`Unless we rename the whole repository.jboss.org we will not rename origin-`

**Comment by ge0ffrey** [comment]
+1 (if the rename the whole, we lose build reproducibility too anyway).

I presume this doesn't affect our local ~/.m2/settings.xml files which might contain a username/password for the deploy servers?

**Comment by psiroky** [comment]
Correct, the server IDs are still the same (jboss-releases-repository and jboss-snapshots-repository), so this change does not affet ~/.m2/settings.xml.

**Pull request merged**
