### PR TITLE
- DROOLS-972: adding deltaspike core and ctrlcdi-weld dependencies

### PR DESCRIPTION
**Pull request by Salaboy**

### CODE REVIEW

**Comment by Salaboy** [comment]
I'm not sure about the definition of deltaspike dependency in our parent pom. Mostly because it is also defined in the jboss-integration parent pom, but it doesn't seem that we can use those variables in our projects.

**Comment by psiroky** [comment]
You can reuse the property coming from https://github.com/jboss-integration/jboss-integration-platform-bom/blob/master/pom.xml#L191

**Comment by Salaboy** [comment]
For some reason I couldn't, but in theory if I just remove the variable definition should it work?

**Comment by psiroky** [comment]
Oh, my bad. This will be possible once we merge #166. Then you can simply remove the property....

**Comment by mariofusco** [comment]
Merged by https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/commit/ff984b29f

**Pull request closed without merging**
