### PR TITLE
UF-295 - Updrading lucene to 5.3.1

### PR DESCRIPTION
**Pull request by mrietveld**
See also: 

- https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/169
- https://github.com/uberfire/uberfire/pull/337
- https://github.com/uberfire/uberfire-extensions/pull/258
- https://github.com/droolsjbpm/kie-wb-common/pull/337
- https://github.com/droolsjbpm/jbpm-designer/pull/220
- https://github.com/droolsjbpm/jbpm-form-modeler/pull/46
- https://github.com/droolsjbpm/jbpm-console-ng/pull/395
- https://github.com/droolsjbpm/drools-wb/pull/156
- https://github.com/droolsjbpm/optaplanner-wb/pull/56
- https://github.com/droolsjbpm/kie-wb-distributions/pull/261

### CODE REVIEW

**Comment by manstis** [comment]
@mrietveld I think you'll need to include ```kie-wb-distributions``` too; for example https://github.com/droolsjbpm/kie-wb-distributions/blob/master/kie-drools-wb/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/backend/server/LuceneConfigProducer.java (and the equivalent in ```kie-wb```).

**Comment by mrietveld** [comment]
@manstis argh.. thanks.

**Comment by mrietveld** [comment]
@porcelli Would you mind going though this? I'm 99.999999% sure that the whole things builds, and that there's a weird jenkins mess-up, with regards to the check-build.

**Comment by manstis** [comment]
+1 to merge (when @porcelli has commented on @mrietveld's question in https://github.com/uberfire/uberfire-extensions/pull/258)

**Pull request merged**
