### PR TITLE
BZ-1274685 - New Repository dialog validation broken when Managed Repository is checked

### PR DESCRIPTION
**Pull request by wmedvede**
(cherry picked from commit ec17dd2bca1a82ee18e7156fc27c85eb6871d341)

### CODE REVIEW

**Comment by wmedvede** [comment]
Peer PR for https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/94

**Comment by manstis** [comment]
+1 to merge.

**Comment by wmedvede** [comment]
The following PR is related to this PR and should be previously

1) https://github.com/uberfire/uberfire-extensions/pull/104

**Comment by wmedvede** [comment]
@manstis 
Hello Mike, would you mind to review this PR?

**Comment by csadilek** [comment]
Thanks.

master: 92c0b0b5b339d469ca381fb067738fad9ea93486

**Pull request closed without merging**
