### PR TITLE
GUVNOR-2296: Upgrade Lienzo to 2.0.192-RC1

### PR DESCRIPTION
**Pull request by manstis**

### CODE REVIEW

**Comment by manstis** [comment]
See https://github.com/uberfire/uberfire-extensions/pull/126

Similar PR to be created for Dash Builder (to follow from @dgutierr)

**Comment by dgutierr** [comment]
Dashbuilder's PR https://github.com/dashbuilder/dashbuilder/pull/68

**Comment by manstis** [comment]
I have compiled from uberfire up to drools-wb with the new version (this covers all use of Lienzo - other than Dash Builder, but @dgutierr says he's also test-compiled that with this newer version successfully)

**Comment by dgutierr** [comment]
+1

**Comment by csadilek** [comment]
master: 37cd993cc6d313529ea8d56073debb18db70a6fa

**Pull request closed without merging**
