### PR TITLE
Remove duplicated script + move some scripts to checks/

### PR DESCRIPTION
**Pull request by psiroky**
I believe the moved (Perl) scripts are all checking something, so better place for them is the checks dir. One of the scripts was also duplicated, so I removed it.

@mrietveld I am doing this as PR to be sure I getting the meaning of the scripts right. Please take a quick look and let me know if you agree with these changes.

### CODE REVIEW

**Comment by yurloc** [comment]
@psiroky `script/repo-dep-tree.pl` tries to read `./repository-list.txt` so the relative path has to be changed to `../repository-list.txt` when the script is moved.

**Comment by psiroky** [comment]
Thanks @yurloc, this (and few other relative paths) should be fixed now.

**Comment by mrietveld** [comment]
@psiroky Looks good, +1

**Comment by psiroky** [comment]
Merged into master.

**Pull request closed without merging**
