### PR TITLE
JBPM-4664:add new module jbpm-console-ng-preferences

### PR DESCRIPTION
**Pull request by bxf12315**
@Salaboy 
Please review it .

### CODE REVIEW

**Comment by mswiderski** [comment]
is this still valid PR or shall it be closed? looks like it's there for a while...

**Comment by Salaboy** [comment]
good question, I think that we can close it

**Comment by bxf12315** [comment]
I thinks it is useful PR, because of our mutil-view mode need it.

**Comment by psiroky** [comment]
I am closing this as all the referenced PRs are now closed as well. Please re-open if case it is still needed.

**Pull request closed without merging**
