### PR TITLE
Upgrade to IP BOM 6.0.0.Final + related fixes

### PR DESCRIPTION
**Pull request by psiroky**
* those removed dependecies are already present in the
   new IP BOM

@mbiarnes please take a look

### CODE REVIEW

**Comment by psiroky** [comment]
Please do not merge yet. It seems the Picketlink downgrade (from 2.6.0.Final to 2.5.4.SP7) is not possible, so I will need to fix that.

**Comment by mbiarnes** [comment]
except the Picketlink problem (that should be solved before merging this) reviewing this PR: +1

**Comment by psiroky** [comment]
This is now ready. PR for kie-wb-common was closed and new one for guvnor created: https://github.com/droolsjbpm/guvnor/pull/213.

**Comment by csadilek** [comment]
master: a7c5e7f18a4ee9f444dab386227a5e450b78017d

**Pull request closed without merging**
