### PR TITLE
Upgrade cargo-maven2-plugin from 1.5.0 to 1.6.2

### PR DESCRIPTION
**Pull request by sutaakar**
Test component - used for controlling of application servers during integration tests.

### CODE REVIEW

**Comment by sutaakar** [comment]
@psiroky Can you please look on this?

**Comment by psiroky** [comment]
This should be fine I believe, let's just run the full build to be sure.

Jenkins execute full downstream build

**Comment by psiroky** [comment]
The failure may be related:
```
java.lang.RuntimeException: java.lang.NullPointerException
	at org.codehaus.cargo.container.internal.http.HttpConnection$1.getPasswordAuthentication(HttpConnection.java:136)
	at java.net.Authenticator.requestPasswordAuthentication(Authenticator.java:317)
	at sun.net.www.protocol.http.HttpURLConnection$1.run(HttpURLConnection.java:453)
	at sun.net.www.protocol.http.HttpURLConnection$1.run(HttpURLConnection.java:448)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.privilegedRequestPasswordAuthentication(HttpURLConnection.java:447)
	at sun.net.www.protocol.http.HttpURLConnection.getServerAuthentication(HttpURLConnection.java:2429)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1719)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.codehaus.cargo.container.internal.http.HttpConnection.connect(HttpConnection.java:258)
	at org.codehaus.cargo.container.internal.http.HttpConnection.post(HttpConnection.java:154)
	at org.codehaus.cargo.container.wildfly.internal.AbstractWildFlyRemoteDeployer.undeployDeployable(AbstractWildFlyRemoteDeployer.java:170)
	at org.codehaus.cargo.container.wildfly.internal.AbstractWildFlyRemoteDeployer.undeploy(AbstractWildFlyRemoteDeployer.java:106)
	at org.kie.server.integrationtests.controller.ContainerRemoteController.undeployWarFile(ContainerRemoteController.java:59)
```

**Comment by sutaakar** [comment]
Yes, that is related to upgrade of Cargo remote deployment for WildFly. Already preparing fix.

**Comment by mswiderski** [comment]
Jenkins execute full downstream build

**Comment by mswiderski** [comment]
@sutaakar @psiroky to me these three failures are completely not related to this change, wdyt?

**Comment by sutaakar** [comment]
@mswiderski I agree

**Comment by psiroky** [comment]
Yeah, the failures does not seem to be related (but we need to make sure they get fixed or at least looked at).

**Comment by sutaakar** [comment]
@psiroky Do you know who to ask to check these issues?

**Comment by psiroky** [comment]
@sutaakar I am not 100 % sure. I think for now it should be enough to e-mail bsig or create JIRAs for these and let project leads distribute the issues to specific people.

**Comment by sutaakar** [comment]
Created respective JIRAs [1] [2]

[1] https://issues.jboss.org/browse/JBPM-5576
[2] https://issues.jboss.org/browse/JBPM-5577

**Comment by psiroky** [comment]
I am merging this since the test failures are really not related and we don't even run the full downstream build regularly, so from that point of view, there is no need to hold off the PR any longer.

**Pull request merged**
