### PR TITLE
[DROOLS-788] add kie-platform-bom

### PR DESCRIPTION
**Pull request by psiroky**
* kie-platform-bom should serve as a replacement for
   kie-parent-with-dependencies for cases where we
   need/want all the versions KIE projects are using
   (even the 3rd party ones like sl4j or commons-io).
   The kie-parent-with-dependencies now simply imports
   that BOM and adds the default junit and mockito deps
   (no change there). The plan is to eventually (for
   version 7.x) remove the kie-parent-with-dependencies
   and use only kie-parent and kie-platfrom-bom.

@ge0ffrey @mbiarnes please take a look and let me know what you think.

### CODE REVIEW

**Comment by ge0ffrey** [comment]
+1 Makes senses (and is as discussed).

I think the next step after this is removing kie-parent-with-dependencies. Less is more: I think we can no longer justify the existence of kie-parent-with-dependencies. Once it's removed, we can probably just rename kie-parent-metadata back to kie-parent.

**Comment by psiroky** [comment]
One minor issue with removing the `kie-parent-with-dependencies` is that is declares two test-scope dependencies - junit and mockito. So once we remove this parent, we will need to include these deps in all the 20 (or so) top-level POM files.

**Comment by ge0ffrey** [comment]
I can live with that. Not everyone might use mockito anyway.

**Comment by psiroky** [comment]
Yes, this is definitely not a blocker. We just need to keep in mind to upgrade POMs. As we discussed I will plan to remove the `kie-parent-with-dependencies` for 7.0 release. I will create JIRA for that and mention that we need to add the dependencies into the top-level POMs.

**Comment by mbiarnes** [comment]
+1

**Comment by psiroky** [comment]
I'll will update the PR so it is mergeable again, test it locally executing the whole build and commit the changes tomorrow if I don't find any issues.

**Comment by psiroky** [comment]
Finally merged and pushed into master. https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/commit/7eed026fb66f4af54075846a9a1f06b46b3d8643

**Pull request closed without merging**
