### PR TITLE
[BZ-996210] upgrade batik from 1.6-1 to 1.7

### PR DESCRIPTION
**Pull request by psiroky**
* the artifacts in version 1.7 (and depMgmt) are
   imported from ip-bom
 * apache-fop, avalon-framework and xmlgraphics-common
   were upgraded as well to aligh the dependencies
   correctly

 * this PR needs to be merged together with the one for `jbpm-designer`

### CODE REVIEW

**Comment by psiroky** [comment]
PR for `jpm-designer`: https://github.com/droolsjbpm/jbpm-designer/pull/50

**Comment by ge0ffrey** [comment]
Can we get this merged?

**Comment by psiroky** [comment]
@ge0ffrey I would be more than happy to do that. But we need fixes in jbpm-designer, so @tsurdilo or @jlindop would need to take another look at that.

**Comment by psiroky** [comment]
I am closing this. It has been around for more than a year and it will likely never be merged. I am keeping the branch around just in case.

**Pull request closed without merging**
